// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoRental_DVT.Data;

namespace VideoRental_DVT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoRental_DVT.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Age = 33,
                            CustomerName = "Dirk"
                        },
                        new
                        {
                            CustomerId = 2,
                            Age = 25,
                            CustomerName = "Jeff"
                        },
                        new
                        {
                            CustomerId = 3,
                            Age = 18,
                            CustomerName = "Shara"
                        },
                        new
                        {
                            CustomerId = 4,
                            Age = 21,
                            CustomerName = "Amber"
                        });
                });

            modelBuilder.Entity("VideoRental_DVT.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("RentId")
                        .HasColumnType("int");

                    b.Property<bool>("Rented")
                        .HasColumnType("bit");

                    b.Property<int?>("RentedToCustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoId");

                    b.HasIndex("RentedToCustomerId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            Director = "Bob",
                            Price = 22.0,
                            RentId = 1,
                            Rented = true,
                            ReturnDate = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VideoName = "jumanji"
                        },
                        new
                        {
                            VideoId = 2,
                            Director = "David",
                            Price = 12.0,
                            RentId = 2,
                            Rented = true,
                            ReturnDate = new DateTime(2021, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VideoName = "WalkingDead"
                        },
                        new
                        {
                            VideoId = 3,
                            Director = "David",
                            Price = 15.0,
                            RentId = 3,
                            Rented = true,
                            ReturnDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VideoName = "Goodplace"
                        },
                        new
                        {
                            VideoId = 4,
                            Director = "Bob Holand",
                            Price = 5.0,
                            RentId = 4,
                            Rented = true,
                            ReturnDate = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VideoName = "HappyGilmore"
                        },
                        new
                        {
                            VideoId = 5,
                            Director = "Keenen Ivory Wayans",
                            Price = 9.9900000000000002,
                            RentId = 5,
                            Rented = true,
                            ReturnDate = new DateTime(2021, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VideoName = "White chicks"
                        },
                        new
                        {
                            VideoId = 6,
                            Director = "Todd Phillips",
                            Price = 8.0,
                            RentId = 6,
                            Rented = true,
                            ReturnDate = new DateTime(2021, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VideoName = "War dogs"
                        },
                        new
                        {
                            VideoId = 7,
                            Director = "Curtis Hanson",
                            Price = 13.49,
                            Rented = false,
                            VideoName = "8 Mile"
                        },
                        new
                        {
                            VideoId = 8,
                            Director = "Greg Mottola",
                            Price = 9.8000000000000007,
                            Rented = false,
                            VideoName = "Superbad"
                        },
                        new
                        {
                            VideoId = 9,
                            Director = "Robert Luketic",
                            Price = 12.1,
                            RentId = 7,
                            Rented = true,
                            ReturnDate = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VideoName = "21"
                        },
                        new
                        {
                            VideoId = 10,
                            Director = "Phil Lord",
                            Price = 14.5,
                            Rented = false,
                            VideoName = "21 Jumpstreet"
                        },
                        new
                        {
                            VideoId = 11,
                            Director = "Lou Adler",
                            Price = 20.0,
                            RentId = 8,
                            Rented = true,
                            VideoName = "Up In Smoke"
                        },
                        new
                        {
                            VideoId = 12,
                            Director = "Todd Strauss-Schulson",
                            Price = 8.0,
                            RentId = 9,
                            Rented = true,
                            VideoName = "A Very Harold & Kumar Christmas"
                        },
                        new
                        {
                            VideoId = 13,
                            Director = "Martin Scorsese",
                            Price = 8.0,
                            Rented = false,
                            VideoName = "The wolf of wallstreet"
                        });
                });

            modelBuilder.Entity("VideoRental_DVT.Models.Video", b =>
                {
                    b.HasOne("VideoRental_DVT.Models.Customer", "RentedTo")
                        .WithMany("RentedVideos")
                        .HasForeignKey("RentedToCustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
